config/routes.rb
Rails.application.routes.draw do
  root :to => "home#index",
    :protocol => (Rails.application.config.force_ssl ? "https://" : "http://"),
    :as => "root"

  get "/404" => "home#four_oh_four", :via => :all

  get "/rss" => "home#index", :format => "rss"
  get "/hottest" => "home#index", :format => "json"

  get "/page/:page" => "home#index"
  get "/landing" => "home#landing"

  get "/newest" => "home#newest"
  get "/newest/page/:page" => "home#newest"
  get "/newest/:user" => "home#newest_by_user"
  get "/newest/:user/page/:page" => "home#newest_by_user"
  get "/recent" => "home#recent"
  get "/recent/page/:page" => "home#recent"
  get "/hidden" => "home#hidden"
  get "/hidden/page/:page" => "home#hidden"
  get "/saved" => "home#saved"
  get "/saved/page/:page" => "home#saved"

  get "/upvoted" => "home#upvoted"
  get "/upvoted/page/:page" => "home#upvoted"

  get "/top" => "home#top"
  get "/top/page/:page" => "home#top"
  get "/top/:length" => "home#top"
  get "/top/:length/page/:page" => "home#top"

  get "/threads" => "comments#threads"
  get "/threads/:user" => "comments#threads", :as => "user_threads"

  get "/replies" => "replies#all"
  get "/replies/page/:page" => "replies#all"
  get "/replies/comments" => "replies#comments"
  get "/replies/comments/page/:page" => "replies#comments"
  get "/replies/stories" => "replies#stories"
  get "/replies/stories/page/:page" => "replies#stories"
  get "/replies/unread" => "replies#unread"
  get "/replies/unread/page/:page" => "replies#unread"

  get "/login" => "login#index"
  post "/login" => "login#login"
  post "/logout" => "login#logout"
  get "/login/2fa" => "login#twofa"
  post "/login/2fa_verify" => "login#twofa_verify", :as => "twofa_login"

  get "/signup" => "signup#index"
  post "/signup" => "signup#signup"
  get "/signup/invite" => "signup#invite"

  get "/login/forgot_password" => "login#forgot_password",
    :as => "forgot_password"
  post "/login/reset_password" => "login#reset_password",
    :as => "reset_password"
  match "/login/set_new_password" => "login#set_new_password",
    :as => "set_new_password", :via => [:get, :post]

  get "/t/:tag" => "home#tagged", :as => "tag"
  get "/t/:tag/page/:page" => "home#tagged"

  get "/search" => "search#index"
  get "/search/:q" => "search#index"

  resources :stories do
    post "upvote"
    post "downvote"
    post "unvote"
    post "undelete"
    post "hide"
    post "unhide"
    post "save"
    post "unsave"
    get "suggest"
    post "suggest", :action => "submit_suggestions"
  end
  post "/stories/fetch_url_attributes", :format => "json"
  post "/stories/preview" => "stories#preview"
  post "/stories/check_url_dupe" => "stories#check_url_dupe"

  resources :comments do
    member do
      get "reply"
      post "upvote"
      post "downvote"
      post "unvote"

      post "delete"
      post "undelete"
      post "disown"
    end
  end
  get "/comments/page/:page" => "comments#index"
  get "/comments" => "comments#index"

  get "/messages/sent" => "messages#sent"
  get "/messages" => "messages#index"
  post "/messages/batch_delete" => "messages#batch_delete",
    :as => "batch_delete_messages"
  resources :messages do
    post "keep_as_new"
    post "mod_note"
  end

  get "/c/:id" => "comments#redirect_from_short_id"
  get "/c/:id.json" => "comments#show_short_id", :format => "json"

  # deprecated
  get "/s/:story_id/:title/comments/:id" => "comments#redirect_from_short_id"

  get "/s/:id/(:title)" => "stories#show"

  get "/u" => "users#tree"
  get "/u/:username" => "users#show", :as => "user"

  get "/avatars/:username_size.png" => "avatars#show"
  post "/avatars/expire" => "avatars#expire"

  post "/users/:username/ban" => "users#ban", :as => "user_ban"
  post "/users/:username/unban" => "users#unban", :as => "user_unban"
  post "/users/:username/disable_invitation" => "users#disable_invitation",
        :as => "user_disable_invite"
  post "/users/:username/enable_invitation" => "users#enable_invitation",
        :as => "user_enable_invite"

  get "/settings" => "settings#index"
  post "/settings" => "settings#update"
  post "/settings/delete_account" => "settings#delete_account",
    :as => "delete_account"
  get "/settings/2fa" => "settings#twofa", :as => "twofa"
  post "/settings/2fa_auth" => "settings#twofa_auth", :as => "twofa_auth"
  get "/settings/2fa_enroll" => "settings#twofa_enroll",
    :as => "twofa_enroll"
  get "/settings/2fa_verify" => "settings#twofa_verify",
    :as => "twofa_verify"
  post "/settings/2fa_update" => "settings#twofa_update",
    :as => "twofa_update"

  post "/settings/pushover_auth" => "settings#pushover_auth"
  get "/settings/pushover_callback" => "settings#pushover_callback"
  get "/settings/github_auth" => "settings#github_auth"
  get "/settings/github_callback" => "settings#github_callback"
  post "/settings/github_disconnect" => "settings#github_disconnect"
  get "/settings/twitter_auth" => "settings#twitter_auth"
  get "/settings/twitter_callback" => "settings#twitter_callback"
  post "/settings/twitter_disconnect" => "settings#twitter_disconnect"

  get "/filters" => "filters#index"
  post "/filters" => "filters#update"

  get "/tags" => "tags#index"
  get "/tags.json" => "tags#index", :format => "json"
  get "/tags/new" => "tags#new", :as => "new_tag"
  get "/tags/:id/edit" => "tags#edit", :as => "edit_tag"
  post "/tags" => "tags#create"
  post "/tags/:id" => "tags#update", :as => "update_tag"

  post "/invitations" => "invitations#create"
  get "/invitations" => "invitations#index"
  get "/invitations/request" => "invitations#build"
  post "/invitations/create_by_request" => "invitations#create_by_request",
    :as => "create_invitation_by_request"
  get "/invitations/confirm/:code" => "invitations#confirm_email"
  post "/invitations/send_for_request" => "invitations#send_for_request",
    :as => "send_invitation_for_request"
  get "/invitations/:invitation_code" => "signup#invited"
  post "/invitations/delete_request" => "invitations#delete_request",
    :as => "delete_invitation_request"

  get "/hats" => "hats#index"
  get "/hats/build_request" => "hats#build_request",
    :as => "request_hat"
  post "/hats/create_request" => "hats#create_request",
    :as => "create_hat_request"
  get "/hats/requests" => "hats#requests_index"
  post "/hats/approve_request/:id" => "hats#approve_request",
    :as => "approve_hat_request"
  post "/hats/reject_request/:id" => "hats#reject_request",
    :as => "reject_hat_request"

  get "/moderations" => "moderations#index"
  get "/moderations/page/:page" => "moderations#index"
  get "/moderators" => "users#tree", :moderators => true

  get "/mod" => "mod#index"
  get "/mod/flagged/:period"   => "mod#flagged",   :as => "mod_flagged"
  get "/mod/downvoted/:period" => "mod#downvoted", :as => "mod_downvoted"
  get "/mod/commenters/:period" => "mod#commenters", :as => "mod_commenters"
  get "/mod/notes(/:period)" => "mod_notes#index", :as => "mod_notes"
  post "/mod/notes" => "mod_notes#create"

  get "/privacy" => "home#privacy"
  get "/about" => "home#about"
  get "/chat" => "home#chat"

  post "broadcast" => "messages#broadcast"
end

app/controllers/settings_controller.rb
class SettingsController < ApplicationController
  before_action :require_logged_in_user

  TOTP_SESSION_TIMEOUT = (60 * 15)

  def index
    @title = "Account Settings"

    @edit_user = @user.dup
  end

  def delete_account
    unless params[:user][:i_am_sure].present?
      flash[:error] = 'You did not check the "I am sure" checkbox.'
      return redirect_to settings_path
    end
    unless @user.try(:authenticate, params[:user][:password].to_s)
      flash[:error] = "Your password could not be verified."
      return redirect_to settings_path
    end

    @user.delete!
    if params[:user][:disown].present?
      InactiveUser.disown_all_by_author! @user
    end
    reset_session
    flash[:success] = "Your account has been deleted."
    return redirect_to "/"
  end

  def update
    previous_username = @user.username
    @edit_user = @user.clone

    if params[:user][:password].empty? ||
       @user.authenticate(params[:current_password].to_s)
      if @edit_user.update(user_params)
        if @edit_user.username != previous_username
          Moderation.create!(
            is_from_suggestions: true,
            user: @edit_user,
            action: "changed own username from \"#{previous_username}\" " <<
                    "to \"#{@edit_user.username}\"",
          )
        end
        flash.now[:success] = "Successfully updated settings."
        @user = @edit_user
      end
    else
      flash[:error] = "Your current password was not entered correctly."
    end

    render :action => "index"
  end

  def twofa
    @title = "Two-Factor Authentication"
  end

  def twofa_auth
    if @user.authenticate(params[:user][:password].to_s)
      session[:last_authed] = Time.now.to_i
      session.delete(:totp_secret)

      if @user.has_2fa?
        @user.disable_2fa!
        flash[:success] = "Two-Factor Authentication has been disabled."
        return redirect_to "/settings"
      else
        return redirect_to twofa_enroll_url
      end
    else
      flash[:error] = "Your password was not correct."
      return redirect_to twofa_url
    end
  end

  def twofa_enroll
    @title = "Two-Factor Authentication"

    if (Time.now.to_i - session[:last_authed].to_i) > TOTP_SESSION_TIMEOUT
      flash[:error] = "Your enrollment period timed out."
      return redirect_to twofa_url
    end

    if !session[:totp_secret]
      session[:totp_secret] = ROTP::Base32.random_base32
    end

    totp = ROTP::TOTP.new(session[:totp_secret], :issuer => Rails.application.name)
    totp_url = totp.provisioning_uri(@user.email)

    # no option for inline svg, so just strip off leading <?xml> tag
    qrcode = RQRCode::QRCode.new(totp_url)
    qr = qrcode.as_svg(offset: 0,
                       color: "000",
                       module_size: 5,
                       shape_rendering: "crispEdges").gsub(/^<\?xml.*>/, "")

    @qr_svg = "<a href=\"#{totp_url}\">#{qr}</a>"
  end

  def twofa_verify
    @title = "Two-Factor Authentication"

    if ((Time.now.to_i - session[:last_authed].to_i) > TOTP_SESSION_TIMEOUT) ||
       !session[:totp_secret]
      flash[:error] = "Your enrollment period timed out."
      return redirect_to twofa_url
    end
  end

  def twofa_update
    if ((Time.now.to_i - session[:last_authed].to_i) > TOTP_SESSION_TIMEOUT) ||
       !session[:totp_secret]
      flash[:error] = "Your enrollment period timed out."
      return redirect_to twofa_url
    end

    @user.totp_secret = session[:totp_secret]
    if @user.authenticate_totp(params[:totp_code])
      # re-roll, just in case
      @user.session_token = nil
      @user.save!

      session[:u] = @user.session_token

      flash[:success] = "Two-Factor Authentication has been enabled on your account."
      session.delete(:totp_secret)
      return redirect_to "/settings"
    else
      flash[:error] = "Your TOTP code was invalid, please verify the " <<
                      "current code in your TOTP application."
      return redirect_to twofa_verify_url
    end
  end

  # external services

  def pushover_auth
    if !Pushover.SUBSCRIPTION_CODE
      flash[:error] = "This site is not configured for Pushover"
      return redirect_to "/settings"
    end

    session[:pushover_rand] = SecureRandom.hex

    return redirect_to Pushover.subscription_url(
      :success => "#{Rails.application.root_url}settings/pushover_callback?" <<
        "rand=#{session[:pushover_rand]}",
      :failure => "#{Rails.application.root_url}settings/",
    )
  end

  def pushover_callback
    if !session[:pushover_rand].to_s.present?
      flash[:error] = "No random token present in session"
      return redirect_to "/settings"
    end

    if !params[:rand].to_s.present?
      flash[:error] = "No random token present in URL"
      return redirect_to "/settings"
    end

    if params[:rand].to_s != session[:pushover_rand].to_s
      raise "rand param #{params[:rand].inspect} != #{session[:pushover_rand].inspect}"
    end

    @user.pushover_user_key = params[:pushover_user_key].to_s
    @user.save!

    if @user.pushover_user_key.present?
      flash[:success] = "Your account is now setup for Pushover notifications."
    else
      flash[:success] = "Your account is no longer setup for Pushover notifications."
    end

    return redirect_to "/settings"
  end

  def github_auth
    session[:github_state] = SecureRandom.hex
    return redirect_to Github.oauth_auth_url(session[:github_state])
  end

  def github_callback
    if !session[:github_state].present? ||
       !params[:code].present? ||
       (params[:state].to_s != session[:github_state].to_s)
      flash[:error] = "Invalid OAuth state"
      return redirect_to "/settings"
    end

    session.delete(:github_state)

    tok, username = Github.token_and_user_from_code(params[:code])
    if tok.present? && username.present?
      @user.github_oauth_token = tok
      @user.github_username = username
      @user.save!
      flash[:success] = "Your account has been linked to GitHub user #{username}."
    else
      return github_disconnect
    end

    return redirect_to "/settings"
  end

  def github_disconnect
    @user.github_oauth_token = nil
    @user.github_username = nil
    @user.save!
    flash[:success] = "Your GitHub association has been removed."
    return redirect_to "/settings"
  end

  def twitter_auth
    session[:twitter_state] = SecureRandom.hex
    return redirect_to Twitter.oauth_auth_url(session[:twitter_state])
  rescue OAuth::Unauthorized
    flash[:error] = "Twitter says we're not authenticating properly, please message the admin"
    return redirect_to "/settings"
  end

  def twitter_callback
    if session[:twitter_state].blank? ||
       (params[:state].to_s != session[:twitter_state].to_s)
      flash[:error] = "Invalid OAuth state"
      return redirect_to "/settings"
    end

    session.delete(:twitter_state)

    tok, sec, username = Twitter.token_secret_and_user_from_token_and_verifier(
      params[:oauth_token], params[:oauth_verifier])
    if tok.present? && username.present?
      @user.twitter_oauth_token = tok
      @user.twitter_oauth_token_secret = sec
      @user.twitter_username = username
      @user.save!
      flash[:success] = "Your account has been linked to Twitter user @#{username}."
    else
      return twitter_disconnect
    end

    return redirect_to "/settings"
  end

  def twitter_disconnect
    @user.twitter_oauth_token = nil
    @user.twitter_username = nil
    @user.twitter_oauth_token_secret = nil
    @user.save!
    flash[:success] = "Your Twitter association has been removed."
    return redirect_to "/settings"
  end

private

  def user_params
    params.require(:user).permit(
      :first_name, :last_name, :username, :email, :password, :password_confirmation, :about,
      :email_replies, :email_messages, :email_mentions,
      :pushover_replies, :pushover_messages, :pushover_mentions,
      :mailing_list_mode, :show_avatars, :show_story_previews,
      :show_submitted_story_threads
    )
  end
end

app/views/settings/index.html.erb
<div class="box wide">
  <div class="legend right">
    <a href="/filters">Filtered Tags</a>
    |
    <%= link_to "Logout", { :controller => "login", :action => "logout" },
      :data => { :confirm => "Are you sure you want to logout?" },
      :method => "post" %>
  </div>
  <div class="legend">
    Account Settings (<a href="/u/<%= @user.username %>">View Profile</a>)
  </div>

  <%= form_with :model => @edit_user, :url => settings_path, :method => :post,
  :id => "edit_user" do |f| %>
    <%= error_messages_for f.object %>

    <div class="boxline">
      <%= f.label :first_name, "First Name:", :class => "required" %>
      <%= f.text_field :first_name, :size => 40 %>
    </div>

    <div class="boxline">
      <%= f.label :first_name, "Last Name:", :class => "required" %>
      <%= f.text_field :last_name, :size => 40 %>
    </div>

    <div class="boxline">
      <%= f.label :current_password, "Current Password:",
        :class => "required" %>
    <%= f.password_field :current_password, :name => "current_password", :size => 30 %>
    </div>

    <div class="boxline">
      <%= f.label :password, "New Password:", :class => "required" %>
      <%= f.password_field :password, :size => 40, :autocomplete => "off" %>
    </div>

    <div class="boxline">
      <%= f.label :password_confirmation, "Confirm Password:",
        :class => "required" %>
      <%= f.password_field :password_confirmation, :size => 40,
        :autocomplete => "off" %>
    </div>

    <div class="boxline">
      <%= f.label :email, "E-mail Address:", :class => "required" %>
      <%= f.email_field :email, :size => 40 %>
    </div>

    <div class="boxline">
      <%= f.label :about, "About:", :class => "required" %>
      <%= f.text_area :about, :size => "100x5", :style => "width: 600px;" %>
    </div>

    <div class="box">
      <div class="boxline markdown_help_toggler" style="margin-left: 9em;
      width: 600px;">

        <div style="clear: both;"></div>

        <%= render :partial => "global/markdownhelp" %>
      </div>
    </div>

    <p>
    <%= f.submit "Save Account Settings" %>
    </p>

   
    <br>

  
    <div class="legend">
      Miscellaneous Settings
    </div>

    <div class="boxline">
      <%= f.label :show_story_previews, "Show Story Previews:",
        :class => "required" %>
      <%= f.check_box :show_story_previews %>
    </div>

   
    <br>
    <%= f.submit "Save All Settings" %>
  <% end %>

  <br>
  <br>

  <a name="invite"></a>
  <div class="legend">
    Invite a New User
  </div>

  <% if @user.can_invite? %>
    <%= render :partial => "users/invitationform" %>
  <% else %>
      You cannot send invitations: <%= @user.disabled_invite_reason %>
  <% end %>

  <br>
  <br>

  <div class="deletion">
      <%= form_with :model => @edit_user, :url => delete_account_path, :method => :post,
            :id => "delete_user" do |f| %>
      <div class="legend">
        Delete Account
      </div>

      <p>
      To permanently delete your account, verify your current password below.
      </p>
      <ul>
        <li>Your account will be put into a deleted state.</li>
        <li>Your username will remain reserved and will not be available for any other account.</li>
        <li>Your private messages will be deleted.</li>
        <li>Your submitted stories will not be deleted.</li>
        <li>
          Your comments with negative scores will be deleted, and you can check
          "disown comments" below if you want all of your comments to change to
          list <a href="/u/inactive-user">inactive-user</a> as the author
          instead of your username.
        </li>
      </ul>

      <div class="boxline">
        <%= f.label :password, "Verify Password:", :class => "required" %>
        <%= f.password_field :password, :size => 40, :autocomplete => "off" %>
      </div>
      <div class="boxline">
        <%= f.label :i_am_sure, "I am sure:", :class => "required" %>
        <%= f.check_box :i_am_sure %>
        <br />
        <%= f.label :disown, "Disown Comments:" %>
        <%= f.check_box :disown %> (optional)
      </div>
      <%= f.submit "Yes, Delete My Account", :class => "deletion" %>
    <% end %>
  </div>
</div>

app/views/settings/twofa.html.erb
<div class="box wide">
  <div class="legend right">
    <a href="/settings">Back to Settings</a>
  </div>
  <div class="legend">
    <%= @title %>
  </div>

  <%= form_with :model => @user, :url => twofa_auth_url, :method => :post do |f| %>
    <p>
    <% if @user.has_2fa? %>
      To turn off two-factor authentication for your account, enter your
      current password:
    <% else %>
      To begin the two-factor authentication enrollment for your account,
      enter your current password:
    <% end %>
    </p>

    <div class="boxline">
      <%= f.label :password, "Current Password:", :class => "required" %>
      <%= f.password_field :password, :size => 40, :autocomplete => "off" %>
    </div>

    <p>
    <% if @user.has_2fa? %>
      <%= f.submit "Disable Two-Factor Authentication" %>
    <% else %>
      <%= f.submit "Continue" %>
    <% end %>
  <% end %>
</div>

app/views/settings/twofa_enroll.html.erb
<div class="box wide">
  <div class="legend right">
    <a href="/settings">Back to Settings</a>
  </div>
  <div class="legend">
    <%= @title %>
  </div>

  <p>
  Scan the QR code below or click on it to open in your Google authenticator application
  
  </p>

  <%= raw @qr_svg %>

  <p>
  Once you have finished registering with your Google authenticator application, proceed to
  the next screen to verify your current code and actually enable
  Two-Factor Authentication on your account.
  </p>

  <p>
  <%= button_to "Verify and Enable", twofa_verify_url, :method => :get %>
</div>

app/views/settings/twofa_verify.html.erb
<div class="box wide">
  <div class="legend right">
    <a href="/settings">Back to Settings</a>
  </div>
  <div class="legend">
    <%= @title %>
  </div>

  <%= form_with url: twofa_update_url do |f| %>
    <p>
    To enable Two-Factor Authentication on your account using your new TOTP
    secret, enter the six-digit code from your TOTP application:
    </p>

    <div class="boxline">
      <%= f.label :totp_code, "TOTP Code:", :class => "required" %>
      <%= f.number_field :totp_code, :size => 10, :autocomplete => "off",
          :autofocus => true, :class => "totp_code" %>
    </div>

    <p>
    <%= f.submit "Verify and Enable" %>
  <% end %>
</div>