config/routes.rb
Rails.application.routes.draw do
  root :to => "home#index",
    :protocol => (Rails.application.config.force_ssl ? "https://" : "http://"),
    :as => "root"

  get "/404" => "home#four_oh_four", :via => :all

  get "/rss" => "home#index", :format => "rss"
  get "/hottest" => "home#index", :format => "json"

  get "/page/:page" => "home#index"
  get "/landing" => "home#landing"

  get "/newest" => "home#newest"
  get "/newest/page/:page" => "home#newest"
  get "/newest/:user" => "home#newest_by_user"
  get "/newest/:user/page/:page" => "home#newest_by_user"
  get "/recent" => "home#recent"
  get "/recent/page/:page" => "home#recent"
  get "/hidden" => "home#hidden"
  get "/hidden/page/:page" => "home#hidden"
  get "/saved" => "home#saved"
  get "/saved/page/:page" => "home#saved"

  get "/upvoted" => "home#upvoted"
  get "/upvoted/page/:page" => "home#upvoted"

  get "/top" => "home#top"
  get "/top/page/:page" => "home#top"
  get "/top/:length" => "home#top"
  get "/top/:length/page/:page" => "home#top"

  get "/threads" => "comments#threads"
  get "/threads/:user" => "comments#threads", :as => "user_threads"

  get "/replies" => "replies#all"
  get "/replies/page/:page" => "replies#all"
  get "/replies/comments" => "replies#comments"
  get "/replies/comments/page/:page" => "replies#comments"
  get "/replies/stories" => "replies#stories"
  get "/replies/stories/page/:page" => "replies#stories"
  get "/replies/unread" => "replies#unread"
  get "/replies/unread/page/:page" => "replies#unread"

  get "/login" => "login#index"
  post "/login" => "login#login"
  post "/logout" => "login#logout"
  get "/login/2fa" => "login#twofa"
  post "/login/2fa_verify" => "login#twofa_verify", :as => "twofa_login"

  get "/signup" => "signup#index"
  post "/signup" => "signup#signup"
  get "/signup/invite" => "signup#invite"

  get "/login/forgot_password" => "login#forgot_password",
    :as => "forgot_password"
  post "/login/reset_password" => "login#reset_password",
    :as => "reset_password"
  match "/login/set_new_password" => "login#set_new_password",
    :as => "set_new_password", :via => [:get, :post]

  get "/t/:tag" => "home#tagged", :as => "tag"
  get "/t/:tag/page/:page" => "home#tagged"

  get "/search" => "search#index"
  get "/search/:q" => "search#index"

  resources :stories do
    post "upvote"
    post "downvote"
    post "unvote"
    post "undelete"
    post "hide"
    post "unhide"
    post "save"
    post "unsave"
    get "suggest"
    post "suggest", :action => "submit_suggestions"
  end
  post "/stories/fetch_url_attributes", :format => "json"
  post "/stories/preview" => "stories#preview"
  post "/stories/check_url_dupe" => "stories#check_url_dupe"

  resources :comments do
    member do
      get "reply"
      post "upvote"
      post "downvote"
      post "unvote"

      post "delete"
      post "undelete"
      post "disown"
    end
  end
  get "/comments/page/:page" => "comments#index"
  get "/comments" => "comments#index"

  get "/messages/sent" => "messages#sent"
  get "/messages" => "messages#index"
  post "/messages/batch_delete" => "messages#batch_delete",
    :as => "batch_delete_messages"
  resources :messages do
    post "keep_as_new"
    post "mod_note"
  end

  get "/c/:id" => "comments#redirect_from_short_id"
  get "/c/:id.json" => "comments#show_short_id", :format => "json"

  # deprecated
  get "/s/:story_id/:title/comments/:id" => "comments#redirect_from_short_id"

  get "/s/:id/(:title)" => "stories#show"

  get "/u" => "users#tree"
  get "/u/:username" => "users#show", :as => "user"

  get "/avatars/:username_size.png" => "avatars#show"
  post "/avatars/expire" => "avatars#expire"

  post "/users/:username/ban" => "users#ban", :as => "user_ban"
  post "/users/:username/unban" => "users#unban", :as => "user_unban"
  post "/users/:username/disable_invitation" => "users#disable_invitation",
        :as => "user_disable_invite"
  post "/users/:username/enable_invitation" => "users#enable_invitation",
        :as => "user_enable_invite"

  get "/settings" => "settings#index"
  post "/settings" => "settings#update"
  post "/settings/delete_account" => "settings#delete_account",
    :as => "delete_account"
  get "/settings/2fa" => "settings#twofa", :as => "twofa"
  post "/settings/2fa_auth" => "settings#twofa_auth", :as => "twofa_auth"
  get "/settings/2fa_enroll" => "settings#twofa_enroll",
    :as => "twofa_enroll"
  get "/settings/2fa_verify" => "settings#twofa_verify",
    :as => "twofa_verify"
  post "/settings/2fa_update" => "settings#twofa_update",
    :as => "twofa_update"

  post "/settings/pushover_auth" => "settings#pushover_auth"
  get "/settings/pushover_callback" => "settings#pushover_callback"
  get "/settings/github_auth" => "settings#github_auth"
  get "/settings/github_callback" => "settings#github_callback"
  post "/settings/github_disconnect" => "settings#github_disconnect"
  get "/settings/twitter_auth" => "settings#twitter_auth"
  get "/settings/twitter_callback" => "settings#twitter_callback"
  post "/settings/twitter_disconnect" => "settings#twitter_disconnect"

  get "/filters" => "filters#index"
  post "/filters" => "filters#update"

  get "/tags" => "tags#index"
  get "/tags.json" => "tags#index", :format => "json"
  get "/tags/new" => "tags#new", :as => "new_tag"
  get "/tags/:id/edit" => "tags#edit", :as => "edit_tag"
  post "/tags" => "tags#create"
  post "/tags/:id" => "tags#update", :as => "update_tag"

  post "/invitations" => "invitations#create"
  get "/invitations" => "invitations#index"
  get "/invitations/request" => "invitations#build"
  post "/invitations/create_by_request" => "invitations#create_by_request",
    :as => "create_invitation_by_request"
  get "/invitations/confirm/:code" => "invitations#confirm_email"
  post "/invitations/send_for_request" => "invitations#send_for_request",
    :as => "send_invitation_for_request"
  get "/invitations/:invitation_code" => "signup#invited"
  post "/invitations/delete_request" => "invitations#delete_request",
    :as => "delete_invitation_request"

  get "/hats" => "hats#index"
  get "/hats/build_request" => "hats#build_request",
    :as => "request_hat"
  post "/hats/create_request" => "hats#create_request",
    :as => "create_hat_request"
  get "/hats/requests" => "hats#requests_index"
  post "/hats/approve_request/:id" => "hats#approve_request",
    :as => "approve_hat_request"
  post "/hats/reject_request/:id" => "hats#reject_request",
    :as => "reject_hat_request"

  get "/moderations" => "moderations#index"
  get "/moderations/page/:page" => "moderations#index"
  get "/moderators" => "users#tree", :moderators => true

  get "/mod" => "mod#index"
  get "/mod/flagged/:period"   => "mod#flagged",   :as => "mod_flagged"
  get "/mod/downvoted/:period" => "mod#downvoted", :as => "mod_downvoted"
  get "/mod/commenters/:period" => "mod#commenters", :as => "mod_commenters"
  get "/mod/notes(/:period)" => "mod_notes#index", :as => "mod_notes"
  post "/mod/notes" => "mod_notes#create"

  get "/privacy" => "home#privacy"
  get "/about" => "home#about"
  get "/chat" => "home#chat"

  post "broadcast" => "messages#broadcast"
end

app/controllers/stories_controller.rb
class StoriesController < ApplicationController
  caches_page :show, if: CACHE_PAGE

  before_action :require_logged_in_user_or_400,
                :only => [:upvote, :downvote, :unvote, :hide, :unhide, :preview, :save, :unsave]
  before_action :require_logged_in_user,
                :only => [:destroy, :create, :edit, :fetch_url_attributes, :new, :suggest]
  before_action :verify_user_can_submit_stories, :only => [:new, :create]
  before_action :find_user_story, :only => [:destroy, :edit, :undelete, :update]
  before_action :find_story!, :only => [:suggest, :submit_suggestions]
  around_action :track_story_reads, only: [:show], if: -> { @user.present? }

  def index
    @story = Story.all
  end

  def create
    @title = "Submit Story"
    @cur_url = "/stories/new"

    @story = Story.new(story_params)
    @story.user_id = @user.id

    if @story.valid? && !(@story.already_posted_recently? && !@story.seen_previous)
      if @story.save
        User.all.each do |user|
          next if user == @user
          story_params[:tags_a].each do |tag|
            next unless user.tags.any?
            tag = Tag.find_by(tag: tag)
            next unless tag && user.tags.ids.include?(tag.id)
            @new_message = Message.new(subject: "New Post Notification in #{tag.tag}", body: "A new post has been created by #{@user.username} for (#{tag.tag})", recipient_username: user.username, notification: true)
            @new_message.author_user_id = @user.id
      
            @direction = :out
            @messages = @user.undeleted_received_messages
            @new_message.save
          end
        end
        ReadRibbon.where(user: @user, story: @story).first_or_create
        return redirect_to @story.comments_path
      end
    end

    return render :action => "new"
  end

  def destroy
    if !@story.is_editable_by_user?(@user)
      flash[:error] = "You cannot edit that story."
      return redirect_to "/"
    end

    @story.is_expired = true
    @story.editor = @user

    if params[:reason].present? && @story.user_id != @user.id
      @story.moderation_reason = params[:reason]
    end

    if @story.save(:validate => false)
      Keystore.increment_value_for("user:#{@story.user.id}:stories_deleted")
    end

    redirect_to @story.comments_path
  end

  def edit
    if !@story.is_editable_by_user?(@user)
      flash[:error] = "You cannot edit that story."
      return redirect_to "/"
    end

    @title = "Edit Story"

    if @story.merged_into_story
      @story.merge_story_short_id = @story.merged_into_story.short_id
    end
  end

  def fetch_url_attributes
    s = Story.new
    s.fetching_ip = request.remote_ip
    s.url = params[:fetch_url]

    return render :json => s.fetched_attributes
  end

  def new
    @title = "Submit Story"
    @cur_url = "/stories/new"

    @story = Story.new(user_id: @user.id)
    @story.fetching_ip = request.remote_ip

    if params[:url].present?
      @story.url = params[:url]
      sattrs = @story.fetched_attributes

      if sattrs[:url].present? && @story.url != sattrs[:url]
        flash.now[:notice] = "Note: URL has been changed to fetched " <<
                             "canonicalized version"
        @story.url = sattrs[:url]
      end

      if @story.already_posted_recently?
        # user won't be able to submit this story as new, so just redirect
        # them to the previous story
        flash[:success] = "This URL has already been submitted recently."
        return redirect_to @story.most_recent_similar.comments_path
      end

      # ignore what the user brought unless we need it as a fallback
      @story.title = sattrs[:title]
      if !@story.title.present? && params[:title].present?
        @story.title = params[:title]
      end
    end
  end

  def preview
    @story = Story.new(story_params)
    @story.user_id = @user.id
    @story.previewing = true

    @story.vote = Vote.new(:vote => 1)
    @story.upvotes = 1

    @story.valid?

    @story.seen_previous = true

    return render :action => "new", :layout => false
  end

  def show
    # @story was already loaded by track_story_reads for logged-in users
    @story ||= Story.where(short_id: params[:id]).first!
    if @story.merged_into_story
      flash[:success] = "\"#{@story.title}\" has been merged into this story."
      return redirect_to @story.merged_into_story.comments_path
    end

    if !@story.can_be_seen_by_user?(@user)
      raise ActionController::RoutingError.new("story gone")
    end

    @comments = get_arranged_comments_from_cache(params[:id]) do
      @story.merged_comments
            .includes(:user, :story, :hat, :votes => :user)
            .arrange_for_user(@user)
    end

    @title = @story.title
    @short_url = @story.short_id_url

    respond_to do |format|
      format.html {
        @comment = @story.comments.build

        @meta_tags = {
          "twitter:card" => "summary",
          "twitter:site" => "@lobsters",
          "twitter:title" => @story.title,
          "twitter:description" => @story.comments_count.to_s + " " +
                                   'comment'.pluralize(@story.comments_count),
          "twitter:image" => Rails.application.root_url +
                             "apple-touch-icon-144.png",
        }

        if @story.user.twitter_username.present?
          @meta_tags["twitter:creator"] = "@" + @story.user.twitter_username
        end

        load_user_votes

        render :action => "show"
      }
      format.json {
        render :json => @story.as_json(:with_comments => @comments)
      }
    end
  end

  def suggest
    if !@story.can_have_suggestions_from_user?(@user)
      flash[:error] = "You are not allowed to offer suggestions on that story."
      return redirect_to @story.comments_path
    end

    if (suggested_tags = @story.suggested_taggings.where(:user_id => @user.id)).any?
      @story.tags_a = suggested_tags.map {|st| st.tag.tag }
    end
    if (tt = @story.suggested_titles.where(:user_id => @user.id).first)
      @story.title = tt.title
    end
  end

  def submit_suggestions
    if !@story.can_have_suggestions_from_user?(@user)
      flash[:error] = "You are not allowed to offer suggestions on that story."
      return redirect_to @story.comments_path
    end

    ostory = @story.dup

    @story.title = params[:story][:title]
    if @story.valid?
      dsug = false
      if @story.title != ostory.title
        @story.save_suggested_title_for_user!(@story.title, @user)
        dsug = true
      end

      sugtags = params[:story][:tags_a].reject {|t| t.to_s.strip == "" }.sort
      if @story.tags_a.sort != sugtags
        @story.save_suggested_tags_a_for_user!(sugtags, @user)
        dsug = true
      end

      if dsug
        ostory = @story.reload
        flash[:success] = "Your suggested changes have been noted."
      end
      redirect_to ostory.comments_path
    else
      render :action => "suggest"
    end
  end

  def undelete
    if !(@story.is_editable_by_user?(@user) &&
    @story.is_undeletable_by_user?(@user))
      flash[:error] = "You cannot edit that story."
      return redirect_to "/"
    end

    @story.is_expired = false
    @story.editor = @user

    if @story.save(:validate => false)
      Keystore.increment_value_for("user:#{@story.user.id}:stories_deleted", -1)
    end

    redirect_to @story.comments_path
  end

  def update
    if !@story.is_editable_by_user?(@user)
      flash[:error] = "You cannot edit that story."
      return redirect_to "/"
    end

    @story.is_expired = false
    @story.editor = @user

    if @story.url_is_editable_by_user?(@user)
      @story.attributes = story_params
    else
      @story.attributes = story_params.except(:url)
    end

    if @story.save
      return redirect_to @story.comments_path
    else
      return render :action => "edit"
    end
  end

  def unvote
    if !(story = find_story)
      return render :plain => "can't find story", :status => 400
    end

    Vote.vote_thusly_on_story_or_comment_for_user_because(
      0, story.id, nil, @user.id, nil
    )

    render :plain => "ok"
  end

  def upvote
    if !(story = find_story)
      return render :plain => "can't find story", :status => 400
    end

    Vote.vote_thusly_on_story_or_comment_for_user_because(
      1, story.id, nil, @user.id, nil
    )

    render :plain => "ok"
  end

  def downvote
    if !(story = find_story)
      return render :plain => "can't find story", :status => 400
    end

    if !Vote::STORY_REASONS[params[:reason]]
      return render :plain => "invalid reason", :status => 400
    end

    if !@user.can_downvote?(story)
      return render :plain => "not permitted to downvote", :status => 400
    end

    Vote.vote_thusly_on_story_or_comment_for_user_because(
      -1, story.id, nil, @user.id, params[:reason]
    )

    render :plain => "ok"
  end

  def hide
    if !(story = find_story)
      return render :plain => "can't find story", :status => 400
    end

    HiddenStory.hide_story_for_user(story.id, @user.id)
    ReadRibbon.hide_replies_for(story.id, @user.id)

    render :plain => "ok"
  end

  def unhide
    if !(story = find_story)
      return render :plain => "can't find story", :status => 400
    end

    HiddenStory.where(:user_id => @user.id, :story_id => story.id).delete_all

    render :plain => "ok"
  end

  def save
    if !(story = find_story)
      return render :plain => "can't find story", :status => 400
    end

    SavedStory.save_story_for_user(story.id, @user.id)

    render :plain => "ok"
  end

  def unsave
    if !(story = find_story)
      return render :plain => "can't find story", :status => 400
    end

    SavedStory.where(:user_id => @user.id, :story_id => story.id).delete_all

    render :plain => "ok"
  end

  def check_url_dupe
    @story = Story.new(story_params)
    @story.already_posted_recently?

    respond_to do |format|
      format.html {
        return render :partial => "stories/form_errors", :layout => false,

app/helpers/stories_helper.rb
module StoriesHelper
  def show_guidelines?
    if !@user
      return true
    end

    if @user.stories_submitted_count <= 5
      return true
    end

    if Moderation.joins(:story)
                 .where(
                   "stories.user_id = ? AND moderations.created_at > ?",
                   @user.id,
                   5.days.ago
                 ).exists?
      return true
    end

    false
  end

  def is_unread?(comment)
    if !@user || !@ribbon
      return false
    end

    (comment.created_at > @ribbon.updated_at) && (comment.user_id != @user.id)
  end
end

app/views/stories/_listdetail.html.erb
<%#
  The h-entry, u-report-of, u-url and h-card css classes are necessary
  for the webmentions support. http://microformats.org/wiki/h-entry
%>
<li id="story_<%= story.short_id %>" data-shortid="<%= story.short_id %>"
class="story <%= story.vote && story.vote[:vote] == 1 ? "upvoted" : "" %>
<%= story.vote && story.vote[:vote] == -1 ? "downvoted" : "" %>
<%= story.score <= -1 ? "negative_1" : "" %>
<%= story.score <= -3 ? "negative_3" : "" %>
<%= story.score <= -5 ? "negative_5" : "" %>
<%= story.is_hidden_by_cur_user ? "hidden" : "" %>
<%= story.is_saved_by_cur_user ? "saved" : "" %>
<%= story.is_expired? ? "expired" : "" %>">
<div class="story_liner h-entry">
  <div class="voters">
    <% if @user %>
      <a class="upvoter"></a>
    <% else %>
      <%= link_to "", login_path, :class => "upvoter" %>
    <% end %>
    <div class="score"><%= story.score %></div>
  </div>
  <div class="details">
    <span class="link h-cite u-repost-of">
      <% if story.can_be_seen_by_user?(@user) %>
        <a class="u-url" href="<%= story.url_or_comments_path %>"><%=
          break_long_words(story.title) %></a>
      <% end %>
      <% if story.attachment? %>
        <a class="u-url" target=_blank href="<%= story.attachment_url%><% if defined?(page_number) %>#page=<%=page_number%><% end %>">(view file)</a>
      <% end %>
      <% if story.is_gone? %>
        [Story removed by <%= story.is_moderated? ? "moderator" :
          "original submitter" %>]
      <% end %>
    </span>
    <% if story.markeddown_description.present? %>
      <a class="description_present" title="<%= truncate(story.description,
        :length => 500) %>" href="<%= story.comments_path %>">&#x2636;</a>
    <% end %>
    <% if story.can_be_seen_by_user?(@user) %>
      <span class="tags">
        <% story.tags.each do |tag| %>
          <%= tag_link(tag) %>
        <% end %>
      </span>
      <% if story.domain.present? %>
        <a class="domain" href="<%= story.domain_search_url %>"><%=
          break_long_words(story.domain) %></a>
      <% end %>

      <% if defined?(single_story) && single_story %>
        <% story.merged_stories.not_deleted.each do |ms| %>
          <br>
          <span class="merge"></span>
          <span class="link">
            <a href="<%= ms.url_or_comments_path %>"><%=
              break_long_words(ms.title) %></a>
          </span>
          <span class="tags">
            <% ms.tags.each do |tag| %>
              <a href="<%= tag_path(tag) %>"
                class="<%= tag.css_class %>"
                title="<%= tag.description %>"><%= tag.tag %></a>
            <% end %>
          </span>
          <% if ms.domain.present? %>
            <a class="domain" href="<%= ms.domain_search_url %>"><%=
              break_long_words(ms.domain) %></a>
          <% end %>
          <span class="byline">
            <% if (@user && @user.show_avatars?) || !@user %>
              <a href="/u/<%= ms.user.username %>"><%=
                avatar_img(ms.user, 16) %></a>
            <% end %>
            <% if story.user_is_author? %>
              authored by
            <% else %>
              via
            <% end %>
            <a href="/u/<%= ms.user.username %>" class="u-author h-card <%=
              ms.html_class_for_user %>"><%= ms.user.username %></a>

            <%= time_ago_in_words_label(ms.created_at) %>
            <% if ms.is_editable_by_user?(@user) %>
              |
              <a href="<%= edit_story_path(ms.short_id) %>">edit</a>
            <% end %>
          </span>
        <% end %>
      <% end %>
    <% end %>

    <% if !(defined?(single_story) && single_story) && @user &&
    @user.show_story_previews? %>
      <% if (sc = story.description_or_story_cache(500)).present? %>
        <div class="story_content">
          <%= break_long_words(sc) %>
        </div>
      <% end %>
    <% end %>

    <div class="byline">
      <% if (@user && @user.show_avatars?) || !@user %>
        <a href="/u/<%= story.user.username %>"><%=
          avatar_img(story.user, 16) %></a>
      <% end %>
      <% if story.previewing %>
        <% if story.user_is_author? %>
          authored by
        <% else %>
          via
        <% end %>
        <a class="u-author h-card <%= story.html_class_for_user %>"><%=
          story.user.username %></a>
        just now
      <% else %>
        <% if story.user_is_author? %>
          authored by
        <% else %>
          via
        <% end %>
        <a href="/u/<%= story.user.username %>" class="u-author h-card <%=
          story.html_class_for_user %>"><%= story.user.username %></a>

        <%= time_ago_in_words_label(story.created_at) %>

        <% if story.is_editable_by_user?(@user) %>
          |
          <a href="<%= edit_story_path(story.short_id) %>" class="<%=
            story.has_suggestions? ? "story_has_suggestions" : "" %>">edit</a>
        <% end %>
        <% if story.can_have_suggestions_from_user?(@user) %>
          | <%= link_to "suggest", story_suggest_path(story.short_id),
            :class => "suggester" %>
        <% end %>
        <% if !story.is_gone? && @user %>
          <% if @user && story.vote && story.vote[:vote] == -1 %>
            | <a class="flagger">unflag (<%=
              Vote::STORY_REASONS[story.vote[:reason]].to_s.downcase %>)</a>
          <% elsif @user && @user.can_downvote?(story) %>
            | <a class="flagger">flag</a>
          <% end %>
          <% if story.is_hidden_by_cur_user %>
            | <%= link_to "unhide", story_unhide_path(story.short_id),
              :class => "hider" %>
          <% else %>
            | <%= link_to "hide", story_hide_path(story.short_id),
              :class => "hider" %>
          <% end %>
          <% if defined?(single_story) && single_story && story.hider_count > 0 %>
            (hidden by <%= pluralize(story.hider_count, "user") %>)
          <% end %>
          <% if story.is_saved_by_cur_user %>
            | <%= link_to "unsave", story_unsave_path(story.short_id),
              :class => "saver" %>
          <% else %>
            | <%= link_to "save", story_save_path(story.short_id),
              :class => "saver" %>
          <% end %>
        <% end %>
        
        <% if !story.is_gone? %>
          <span class="comments_label">
            |
            <a href="<%= story.comments_path %>">
            <% if story.comments_count == 0 %>
              no comments</a>
            <% else %>
              <%= story.comments_count %> <%= 'comment'.pluralize(story.comments_count) %></a>
            <% end %>
          </span>
        <% end %>

        <% if defined?(single_story) && single_story &&
        ((story.downvotes > 0 && @user && @user.is_moderator?) ||
        (story.downvotes >= 3 || story.score <= 0)) %>
          | <%= story.vote_summary_for(@user).downcase %>
        <% end %>
      <% end %>
    </div>
  </div>
</div>
<a href="<%= story.comments_path %>" class="mobile_comments <%= story.comments_count == 0 ? "zero" : "" %>" style="display: none;">
  <span><%= story.comments_count %></span>
</a>
</li>

app/views/stories/_similar.html.erb
<ol>
  <% similar.each do |story| %>
    <li>
      <a href="<%= story.url %>" target="_blank"><%= story.title %></a>
      <%= story.user_is_author? ? "authored by" : "via" %>
      <a href="/u/<%= story.user.username %>" class="<%= story.html_class_for_user %>"><%= story.user.username %></a>
      <%= time_ago_in_words_label(story.created_at) %>
      <span>
        |
        <%= story.score %> <%= 'point'.pluralize(story.score) %>
      </span>
      <span class="comments_label">
        |
        <a href="<%= story.comments_path %>">
          <% if story.comments_count == 0 %>
            no comments</a>
          <% else %>
            <%= story.comments_count %> <%= 'comment'.pluralize(story.comments_count) %></a>
          <% end %>
      </span>
    </li>
  <% end %>
</ol>

app/views/stories/edit.html.erb
<div class="box" id="story_box">
  <div class="legend">
    Edit Story
  </div>

  <%= form_with model: @story, :url => story_path(@story.short_id),
  :method => :put, :id => "edit_story" do |f| %>
    <%= render :partial => "stories/form", :locals => { :story => @story,
      :f => f } %>

    <% if @user.is_moderator? %>
      <br />
      <div class="box">
        <div class="boxline">
          <%= f.label :merge_story_short_id, "Merge Into:",
            :class => "required" %>
          <%= f.text_field :merge_story_short_id, :autocomplete => "off",
            :placeholder => "Short id of story into which this story " <<
            "be merged" %>
        </div>
        <div class="boxline">
          <%= f.label :unavailable_at, "Unavailable:",
            :class => "required" %>
          <%= f.check_box :is_unavailable %>
          <%= f.label :unavailable_at, "Source URL is unavailable, " <<
            "enable display of cached text", :class => "normal" %>
        </div>
        <% if @story.user_id != @user.id %>
          <div class="boxline">
            <%= f.label :moderation_reason, "Mod Reason:",
              :class => "required" %>
            <%= f.text_field :moderation_reason %>
          </div>
        <% end %>
      </div>
    <% end %>

    <p></p>

    <div class="box">
      <div class="boxline actions markdown_help_toggler">
        <div class="markdown_help_label">
          Markdown formatting available
        </div>

        <%= f.submit "Save" %>

        <% if @story.is_gone? && @story.is_undeletable_by_user?(@user) %>
          &nbsp; | &nbsp;
          <%= link_to "Undelete", story_undelete_path(@story.short_id),
            :method => :post, :data => {
            :confirm => "Are you sure you want to undelete this story?" },
            :class => "button" %>
        <% elsif !@story.is_gone? %>
          &nbsp; | &nbsp;
          <% if @story.user_id != @user.id && @user.is_moderator? %>
            <%= link_to "Delete", story_path(@story.short_id),
              :method => :delete, :class => "button mod_story_link deletion" %>
          <% else %>
            <%= link_to "Delete", story_path(@story.short_id),
              :method => :delete, :data => {
              :confirm => "Are you sure you want to delete this story?" },
              :class => "button" %>
          <% end %>
        <% end %>

        <div style="clear: both;"></div>

        <%= render :partial => "global/markdownhelp",
          :locals => { allow_images: @story.can_have_images? } %>
      </div>
    </div>
  <% end %>
</div>

app/views/stories/suggest.html.erb
<div class="box" id="story_box">
  <div class="legend">
    Suggest Story Changes
  </div>

  <%= form_with model: @story, :url => story_suggest_path(@story.short_id),
  :method => :post, :html => { :id => "edit_story" } do |f| %>
    <%= render :partial => "stories/form", :locals => { :story => @story,
      :f => f, :suggesting => true } %>

    <p></p>

    <div class="box">
      <div class="boxline actions">
        <%= f.submit "Suggest Changes" %>
        &nbsp;or <a href="<%= story_path(@story.short_id) %>">cancel</a>
      </div>
    </div>
  <% end %>
</div>